accounts/urls.py
from django.urls import path
from .views import RegisterView, MyLoginView, UserDetailView, ListUsers, \
    UserUpdateView, UserChangePasswordView, UserDeletePhotoView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'acc'

urlpatterns = [

    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('<int:pk>/password_change/', UserChangePasswordView.as_view(), name='change_password'),
    path('<int:pk>/profile', UserDetailView.as_view(), name='profile'),
    path('', ListUsers.as_view(), name='list_users'),
    path('<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete_photo', UserDeletePhotoView.as_view(), name='user_delete_photo'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('acc:password_reset_done')),
         name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('acc:password_reset_complete')),
         name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from issue_tracker.views.issues_views import IssuesRedirect
from core.errors import error_404
from django.conf.urls.static import static


handler404 = error_404

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', IssuesRedirect.as_view(), name='main_page'),
    path('issues/', include('issue_tracker.urls.issues_urls', namespace='issues')),
    path('projects/', include('issue_tracker.urls.projects_urls', namespace='projects')),
    path('accounts/', include('accounts.urls', namespace='acc')),
    path('', include('django.contrib.auth.urls')),
    path('api/v1/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings


class Profile(models.Model):
    avatar = models.ImageField(blank=True, upload_to=settings.AVATARS_FOLDER, default=settings.AVATARS_DEFAULT_VALUE)
    github_link = models.URLField(null=True, blank=True)
    personal_info = models.TextField(null=True, blank=True)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.user.get_full_name()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth import get_user_model
from accounts.models import Profile
from.helpers import UserValidationMixin


def get_widget_attrs(**kwargs):
    context = {'class': 'form-control mb-3'}
    if kwargs:
        context.update(kwargs)
    return context


class CreateUserForm(UserValidationMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email']
        widgets = {
            'password1': forms.PasswordInput(attrs=get_widget_attrs(type='password')),
            'password2': forms.PasswordInput(attrs=get_widget_attrs(type='password')),
            'email': forms.EmailInput(attrs=get_widget_attrs(type='email')),
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError('User already exists!')
        return username


class UserUpdateForm(UserValidationMixin, forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name', 'last_name': 'Last Name', 'email': 'Email'}
        widgets = {
            'first_name': forms.TextInput(attrs=get_widget_attrs()),
            'last_name': forms.TextInput(attrs=get_widget_attrs()),
            'email': forms.EmailInput(attrs=get_widget_attrs())
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
        widgets = {
            'github_link': forms.URLInput(attrs=get_widget_attrs()),
            'personal_info': forms.Textarea(attrs=get_widget_attrs()),
            'avatar': forms.FileInput(attrs=get_widget_attrs())
        }


class UserChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(strip=False, widget=forms.PasswordInput(attrs=get_widget_attrs()))
    new_password = forms.CharField(strip=False, widget=forms.PasswordInput(attrs=get_widget_attrs()))
    confirm_new_password = forms.CharField(strip=False, widget=forms.PasswordInput(attrs=get_widget_attrs()))

    class Meta:
        model = get_user_model()
        fields = ['old_password', 'new_password', 'confirm_new_password']

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        confirm_new_password = self.cleaned_data.get('confirm_new_password')
        if new_password and confirm_new_password and new_password != confirm_new_password:
            raise ValidationError('New passwords must be equal!')
        return confirm_new_password

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise ValidationError('Incorrect old password!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('new_password'))
        if commit:
            user.save()
        return user

accounts/views.py
from django.conf import settings
from django.contrib.auth import login, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth import views as auth_views
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect

from issue_tracker.filters.projects_filter import ProjectFilter
from .forms import CreateUserForm, ProfileUpdateForm, UserUpdateForm, UserChangePasswordForm
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from .helpers import AccountsMixin
from django.urls import reverse_lazy
from accounts.helpers import DeleteOldPhotoMixin


class MyLoginView(AccountsMixin, auth_views.LoginView):
    pass


class RegisterView(AccountsMixin, CreateView):
    model = User
    template_name = 'registration/registration.html'
    form_class = CreateUserForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user/detail.html'
    context_object_name = 'user_obj'
    projects = None

    def get_pagination_context(self):
        paginator = Paginator(self.get_projects(), 5)
        page = paginator.get_page(self.request.GET.get('page', 1))
        context = {'paginator': paginator, 'is_paginated': page.has_other_pages(), 'page_obj': page}

        return context

    def get_projects(self):
        return self.object.projects.all()

    def get_context_data(self, **kwargs):
        kwargs['my_filter'] = ProjectFilter(self.request.GET, queryset=self.model.objects.all())
        return super(UserDetailView, self).get_context_data(**kwargs, **self.get_pagination_context())


class ListUsers(PermissionRequiredMixin, ListView):
    template_name = 'user/list.html'
    context_object_name = 'users'
    model = User
    paginate_by = 10
    permission_required = 'auth.view_user'


class UserUpdateView(UserPassesTestMixin, DeleteOldPhotoMixin, UpdateView):
    model = get_user_model()
    template_name = 'user/update.html'
    form_class = UserUpdateForm
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.my_form_valid_method(form, profile_form)
        else:
            return self.my_form_invalid_method(form, profile_form)

    def my_form_valid_method(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def my_form_invalid_method(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
            self.delete_old_photo()

        return ProfileUpdateForm(**form_kwargs)

    def get_success_url(self):
        return reverse_lazy('acc:profile', kwargs={'pk': self.object.pk})

    def test_func(self):
        return self.request.user == self.get_object()


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'user/change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('acc:profile', kwargs={'pk': self.object.pk})


class UserDeletePhotoView(DeleteOldPhotoMixin, DeleteView):
    model = User

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        avatar = self.request.POST.get('avatar')
        self.delete_old_photo(avatar=avatar)

        self.object.profile.avatar = settings.AVATARS_DEFAULT_VALUE
        self.object.profile.save()
        return redirect('acc:profile', pk=self.object.pk)

accounts/templates/user/change_password.html
{% extends 'accounts_base.html' %}

{% block content %}
    <div class="container">
        {% include 'partials/back_button.html' %}
        <form action="{% url 'acc:change_password' user_obj.pk %}" method="post">
            {% include 'partials/form.html' %}
        </form>
    </div>
{% endblock %}

accounts/templates/user/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3 mt-2">
            {% if user_obj.profile.avatar %}
                <img class="avatar w-100" src="{{ user_obj.profile.avatar.url }}" height="250" alt="user picture">
            {% endif %}
            {% if user == user_obj %}
                <form action="{% url 'acc:user_delete_photo' user.pk %}" method="post" class="mb-2">
                    {% csrf_token %}
                    <input type="hidden" name="avatar" value="{{ user.profile.avatar.url }}">
                    {% include 'partials/delete_button.html' with btn_text='Delete Photo' additional_classes='w-100' delete_item='avatar' %}
                </form>
                <a class="btn btn-primary w-100" href="{% url 'acc:user_update' user_obj.pk %}">Edit</a>
                <a class="btn btn-primary w-100 mt-2" href="{% url 'acc:change_password' user_obj.pk %}">
                    Change Password
                </a>
            {% endif %}
        </div>
        <div class="col-9">
            <h1>{{ user_obj.username }}'s page</h1>
            <p>Username: {{ user_obj.username }} <a
                    href="{% if not user_obj.profile.github_link %}#{% else %}{{ user_obj.profile.github_link }}{% endif %}">
                <i class="fab fa-github ms-2 github-color"></i></a></p>
            About me:
            <p>
                {{ user_obj.profile.personal_info }}
            </p>
            <p>First name: {{ user_obj.first_name }}</p>
            <p>Last name: {{ user_obj.last_name }}</p>
            <p>Email: {{ user_obj.email }}</p>
        </div>
    </div>
    {% include 'partials/projects_list.html' with projects=page_obj %}
{% endblock %}

accounts/templates/user/list.html
{% extends 'base.html' %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">GitHub <i class="fab fa-github"></i></th>
            <th scope="col">Email</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'acc:profile' user.pk %}">{{ user.username }}</a></td>
                <td>{{ user.profile.github_link }}</td>
                <td>{{ user.email }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

accounts/templates/user/update.html
{% extends 'base.html' %}

{% block content %}
    <div class="mt-3">{% include 'partials/back_button.html' %}</div>
    <h1>Update profile</h1>
    <form action="{% url 'acc:user_update' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partials/form.html' with form=form fields_only=True %}
        {% include 'partials/form.html' with form=profile_form fields_only=True %}
        <br>
        <div class="mb-5">
            {% include 'partials/submit_button.html' %}
        </div>
    </form>
{% endblock %}