accounts/urls.py
from django.urls import path
from .views import RegisterView, MyLoginView, UserDetailView, ListUsers, \
    UserUpdateView, UserChangePasswordView, UserDeletePhotoView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'acc'

urlpatterns = [

    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('<int:pk>/password_change/', UserChangePasswordView.as_view(), name='change_password'),
    path('<int:pk>/profile', UserDetailView.as_view(), name='profile'),
    path('', ListUsers.as_view(), name='list_users'),
    path('<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete_photo', UserDeletePhotoView.as_view(), name='user_delete_photo'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('acc:password_reset_done')),
         name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('acc:password_reset_complete')),
         name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from issue_tracker.views.issues_views import IssuesRedirect
from core.errors import error_404
from django.conf.urls.static import static


handler404 = error_404

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', IssuesRedirect.as_view(), name='main_page'),
    path('issues/', include('issue_tracker.urls.issues_urls', namespace='issues')),
    path('projects/', include('issue_tracker.urls.projects_urls', namespace='projects')),
    path('accounts/', include('accounts.urls', namespace='acc')),
    path('', include('django.contrib.auth.urls')),
    path('api/v1/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Type(models.Model):
    title = models.CharField(max_length=150, null=False, blank=False, verbose_name='Title')

    def __str__(self):
        return self.title


class Status(models.Model):
    title = models.CharField(max_length=150, null=False, blank=False, verbose_name='Title')

    def __str__(self):
        return self.title


class Issue(models.Model):
    summary = models.CharField(max_length=150, verbose_name='Summary')
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT, default=1, related_name='issues',
                               verbose_name='Status')
    type = models.ManyToManyField(Type, default=1, related_name='issues',
                                  verbose_name='Type')
    project = models.ForeignKey('issue_tracker.Project', on_delete=models.CASCADE, default=1, related_name='issues',
                                verbose_name='Project')
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created Date')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated Date')

    def __str__(self):
        return f'{self.pk} {self.summary} {self.created_at.date()} {self.status} {self.type.all()}'


class Project(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    is_deleted = models.BooleanField(default=False)
    users = models.ManyToManyField(get_user_model(), blank=True, related_name='projects')
    create_date = models.DateField(verbose_name='Started Date')
    end_date = models.DateField(null=True, blank=True, verbose_name='End Date')

    def __str__(self):
        return f'{self.title} {self.create_date} {self.end_date}'

    class Meta:
        permissions = [
            ('add_users_to_project', 'Able to add users to project'),
            ('delete_users_from_project', 'Able to delete user from project'),
        ]

issue_tracker/forms/project_form.py
from django.forms.models import ModelForm
from issue_tracker.models import Project
from django import forms
from datetime import date


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        exclude = ['is_deleted', 'users']

        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control mb-3'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control mb-3'
            }),
            'create_date': forms.TextInput(attrs={
                'type': 'date',
                'class': 'form-control mb-3',
                'min': date.today()
            }),
            'end_date': forms.TextInput(attrs={
                'type': 'date',
                'class': 'form-control mb-3',
                'min': date.today()
            })
        }

issue_tracker/views/project_views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from issue_tracker.filters.issues_filter import IssueFilter
from issue_tracker.forms.project_form import ProjectForm
from issue_tracker.helpers.views import SearchView, MembersOperationsMixin
from issue_tracker.models import Project
from issue_tracker.filters.projects_filter import ProjectFilter
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from issue_tracker.helpers.services import ProjectUserPassesTestMixin


class ProjectsList(ListView):
    template_name = 'projects/list.html'
    context_object_name = 'projects'
    model = Project
    ordering = ['end_date', '-create_date']
    filter_object = None
    paginate_by = 5
    extra_context = {'btn_text': 'Filter'}

    def get(self, request, *args, **kwargs):
        self.filter_object = self.get_filter_object()
        return super(ProjectsList, self).get(request, *args, **kwargs)

    def get_filter_object(self):
        return ProjectFilter(self.request.GET, queryset=self.model.objects.filter(is_deleted=False))

    def get_context_data(self, *, object_list=None, **kwargs):
        return super().get_context_data(my_filter=self.filter_object)

    def get_queryset(self):
        return self.filter_object.qs


class ProjectDetail(DetailView):
    model = Project
    template_name = 'projects/detail.html'
    paginate_by = 5

    def get_paginator(self):
        return Paginator(self.get_filter().qs, 5)

    def get_pagination_context(self):
        paginator = self.get_paginator()
        page = paginator.get_page(self.request.GET.get('page', 1))

        context = {
            'is_paginated': page.has_other_pages(),
            'issues': page.object_list,
            'page_obj': page,
            'paginator': paginator
        }

        return context

    def get_issues(self):
        return self.object.issues.filter(is_deleted=False).order_by('-created_at')

    def get_filter(self):
        return IssueFilter(self.request.GET, queryset=self.get_issues())

    def get_context_data(self, **kwargs):
        context = super(ProjectDetail, self).get_context_data(**kwargs)
        project_users = self.object.users.values_list('id', flat=True)
        users_not_in_project = get_user_model().objects.exclude(id__in=project_users)
        context.update({'my_filter': self.get_filter(), 'btn_text': 'Filter', **self.get_pagination_context(),
                        'users_not_in_project': users_not_in_project, 'project_users': project_users})
        return context


class ProjectCreate(PermissionRequiredMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project.html'
    extra_context = {'btn_text': 'Create Project'}
    success_url = reverse_lazy('projects:projects_list')
    object = None
    permission_required = 'issue_tracker.add_project'

    def form_valid(self, form):
        self.object = form.save()
        self.object.users.add(self.request.user)
        return redirect(self.get_success_url())


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project.html'
    extra_context = {'btn_text': 'Update Project'}
    permission_required = 'issue_tracker.change_project'

    def get_form(self, form_class=None):
        form = super().get_form()
        form.fields['create_date'].widget.attrs.update({'min': self.object.create_date})
        form.fields['end_date'].widget.attrs.update({'min': self.object.create_date})
        return form

    def get_success_url(self):
        return reverse('projects:project_detail', kwargs={'pk': self.object.pk})


class ProjectsSearch(SearchView):
    search_fields = ['title', '|description', '|issues__summary']
    search_fields_methods = ['icontains', 'icontains', 'icontains']


class ProjectDelete(ProjectUserPassesTestMixin, PermissionRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('projects:projects_list')
    permission_required = 'issue_tracker.delete_project'

    def delete(self, request, *args, **kwargs):
        project = self.get_object()
        project.is_deleted = True
        project.save()
        return redirect(self.get_success_url())


class ProjectAddMember(MembersOperationsMixin):
    def action(self):
        user = self.get_user()
        self.object.users.add(user)

    def post(self, request, *args, **kwargs):
        self.action()
        return redirect('projects:project_detail', pk=self.object.pk)


class ProjectDelMember(MembersOperationsMixin):
    def action(self):
        user = self.get_user()
        self.object.users.remove(user)

    def get_success_url(self):
        return reverse('projects:project_detail', kwargs={'pk': self.object.pk})

    def get(self, request, *args, **kwargs):
        self.action()
        return redirect(self.get_success_url())

templates/projects/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mt-5">
        <div class="col-9">
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.title }}</h5>
                        <p class="card-text">{{ project.description }}</p>
                        <p class="card-text">
                            <small class="text-muted">
                                Create Date: {{ project.create_date }} <br>
                                End Date: {{ project.end_date }}
                            </small>
                        </p>

                        <div class="flex mt-4">
                            <a href="{% url 'projects:projects_list' %}" class="btn btn-primary">Return to projects</a>

                            {% if perms.issue_tracker.add_issue and user.pk in project_users or user.is_superuser %}
                                <a href="{% url 'projects:issues_create' project_pk=project.pk %}"
                                   class="btn btn-primary ms-4">Add Issue
                                </a>
                            {% endif %}

                        </div>
                        {% if user.pk in project_users or user.is_superuser %}
                            <ul class="ps-0">
                                {% for issue in issues %}
                                    {% include 'partials/issue_detail.html' %}
                                {% endfor %}
                            </ul>
                        {% endif %}
                        {% if user.pk in project_users or user.is_superuser %}
                            {% if is_paginated %}
                                {% include 'partials/pagination.html' %}
                            {% endif %}
                        {% else %}
                            <h3 class="my-4">You cannot see issues of this project because you don't have membership
                                rights</h3>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <ul class="list-group">
                <li class="list-group-item active">Members</li>
                {% if perms.issue_tracker.add_users_to_project and user.pk in project_users or user.is_superuser %}
                    <li class="list-group-item">
                        <button id="openPanel" type="button" class="w-100 addMemberBtn">+ Add New Member</button>
                    </li>
                    {% include 'partials/show_members.html' %}
                {% endif %}

                {% for proj_user in project.users.all %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'acc:profile' proj_user.pk %}">{{ proj_user.username }}</a>
                            {% if perms.issue_tracker.delete_users_from_project and not proj_user == user and user.pk in project_users or user.is_superuser %}
                                <a onclick="return confirm('Are you sure?')"
                                   href="{% url 'projects:project_del_member' project.pk %}?user={{ proj_user.id }}">
                                    <i class="far fa-times-circle"></i>
                                </a>
                            {% endif %}
                        </div>
                    </li>
                {% empty %}
                    <li class="list-group-item">
                        There are no users
                    </li>
                {% endfor %}
            </ul>
            {% include 'partials/filtration.html' %}
        </div>
    </div>
    <script>
        let addBtn = $('#openPanel')
        let newMembersSelect = $('#showNewMember')

        addBtn.click(() => {
            if (newMembersSelect.hasClass('d-none')) {
                newMembersSelect.removeClass('d-none')
                addBtn.text('Close')
            } else {
                newMembersSelect.addClass('d-none')
                addBtn.text('+ Add New Member')
            }
        })

    </script>
{% endblock %}

templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
    {% include 'partials/projects_list.html' %}
{% endblock %}

templates/projects/project.html
{% extends 'base.html' %}

{% block content %}
    <form action="{{ request.get_full_path }}" method="post">
    {% include 'partials/form.html' %}
    </form>
{% endblock %}