accounts/urls.py
from django.urls import path
from .views import RegisterView, MyLoginView, UserDetailView, ListUsers, \
    UserUpdateView, UserChangePasswordView, UserDeletePhotoView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'acc'

urlpatterns = [

    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('<int:pk>/password_change/', UserChangePasswordView.as_view(), name='change_password'),
    path('<int:pk>/profile', UserDetailView.as_view(), name='profile'),
    path('', ListUsers.as_view(), name='list_users'),
    path('<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete_photo', UserDeletePhotoView.as_view(), name='user_delete_photo'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('acc:password_reset_done')),
         name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('acc:password_reset_complete')),
         name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from issue_tracker.views.issues_views import IssuesRedirect
from core.errors import error_404
from django.conf.urls.static import static


handler404 = error_404

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', IssuesRedirect.as_view(), name='main_page'),
    path('issues/', include('issue_tracker.urls.issues_urls', namespace='issues')),
    path('projects/', include('issue_tracker.urls.projects_urls', namespace='projects')),
    path('accounts/', include('accounts.urls', namespace='acc')),
    path('', include('django.contrib.auth.urls')),
    path('api/v1/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issue_tracker/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Type(models.Model):
    title = models.CharField(max_length=150, null=False, blank=False, verbose_name='Title')

    def __str__(self):
        return self.title


class Status(models.Model):
    title = models.CharField(max_length=150, null=False, blank=False, verbose_name='Title')

    def __str__(self):
        return self.title


class Issue(models.Model):
    summary = models.CharField(max_length=150, verbose_name='Summary')
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT, default=1, related_name='issues',
                               verbose_name='Status')
    type = models.ManyToManyField(Type, default=1, related_name='issues',
                                  verbose_name='Type')
    project = models.ForeignKey('issue_tracker.Project', on_delete=models.CASCADE, default=1, related_name='issues',
                                verbose_name='Project')
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created Date')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated Date')

    def __str__(self):
        return f'{self.pk} {self.summary} {self.created_at.date()} {self.status} {self.type.all()}'


class Project(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    is_deleted = models.BooleanField(default=False)
    users = models.ManyToManyField(get_user_model(), blank=True, related_name='projects')
    create_date = models.DateField(verbose_name='Started Date')
    end_date = models.DateField(null=True, blank=True, verbose_name='End Date')

    def __str__(self):
        return f'{self.title} {self.create_date} {self.end_date}'

    class Meta:
        permissions = [
            ('add_users_to_project', 'Able to add users to project'),
            ('delete_users_from_project', 'Able to delete user from project'),
        ]

templates/partials/back_button.html
<a href="{% if back_url %}{{ back_url }}{% else %}{% url 'acc:profile' user_obj.pk %}{% endif %}" class="btn btn-warning mb-3">
    <i class="fas fa-arrow-circle-left"></i> {{ btn_text | default:'Back' }}
</a>

templates/partials/delete_button.html
<button id="delete_{{ delete_item }}" onclick="return confirm('Are you sure?')" class="btn btn-danger {{ additional_classes }}" type="submit">{{ del_btn_text | default:'Delete' }}</button>

templates/partials/filtration.html
<form method="get" class="mt-4" id="filter-form">
    {% for field in my_filter.form %}
        {{ field.label }}
        {{ field }}
    {% endfor %}
    <div class="mt-4">
        {% include 'partials/submit_button.html' %}
    </div>
</form>
<script>

    const getParameter = (jQueryItem) => {
        return `${jQueryItem.attr("name")}=${jQueryItem.val()}`
    }

    $(function () {
        let location = '?';
        const form = $("#filter-form");
        form.submit(function (e) {
            const formChildren = form.children();
            e.preventDefault()
            for (let i = 0; i < formChildren.length; i++) {
                const jQueryItem = $(formChildren[i])
                if (jQueryItem.val() !== "") {
                    if (location === "?") {
                        location += getParameter(jQueryItem)
                    } else {
                        location += `&${getParameter(jQueryItem)}`
                    }
                }
            }
            window.location.href = location;
            return true;
        });
    });
</script>

templates/partials/form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}">
        {% csrf_token %}
{% endif %}

        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}

        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}

            {{ field.label }}
            {{ field }}
        {% endfor %}

{% if not fields_only %}
        <br/>
        {% include 'partials/submit_button.html' %}
    </form>
{% endif %}

templates/partials/github_icon.html
<a href="{% if not user_obj.profile.github_link %}#{% else %}{{ user_obj.profile.github_link }}{% endif %}">
    <i class="fab fa-github ms-2 github-color"></i></a>

templates/partials/issue_detail.html
<div class="card my-4">
    <div class="card-header">
        <a href="{% url 'issues:issues_detail' issue.pk %}">
            {{ issue.summary }}
        </a>
    </div>
    <div class="card-body">
        <div class="card-title">
            Types:
            <ul>
                {% for type in issue.type.all %}
                    <li>{{ type }}</li>
                {% endfor %}
            </ul>
            Status: {{ issue.status }}
        </div>
        <label>
            <textarea class="card-text border border-2 border-warning" cols="50" rows="7"
                      disabled>{{ issue.description }}</textarea>
        </label>
        <div class="datetime_block my-4">
            Created: {{ issue.created_at }} <br>
            Updated: {{ issue.updated_at }}
        </div>

            {% if not project_users or user.pk in project_users or user.is_superuser %}
                <div class="d-flex">
                    <a href="{% url 'issues:issues_update' pk=issue.pk %}" class="btn btn-primary me-3">Edit</a>

                    {% if perms.issue_tracker.delete_issue %}
                        <form action="{% url 'issues:issues_delete' pk=issue.pk %}" method="post">
                            {% csrf_token %}
                            {% include 'partials/delete_button.html' %}
                        </form>
                    {% endif %}

                </div>
            {% endif %}
    </div>
</div>

templates/partials/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'issues:issues_list' %}">Issue Tracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                {% if perms.auth.view_user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'acc:list_users' %}">Users</a>
                    </li>
                {% endif %}

                {% if perms.issue_tracker.add_project %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'projects:project_create' %}">Create Project</a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'projects:projects_list' %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'issues:issues_list' %}">Issues</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'acc:logout' %}"
                           onclick="return confirm('Are you sure?')">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'acc:profile' user.pk %}">Hello {{ user }}!</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="{% url 'acc:login' %}{% if next_url %}?next={{ next_url }}{% endif %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                           href="{% url 'acc:register' %}{% if next_url %}?next={{ next_url }}{% endif %}">Register</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'issues:issues_list' %}"></a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                {% include 'partials/search.html' %}
            {% endif %}
        </div>
    </div>
</nav>

templates/partials/pagination.html
<div class="d-flex justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>
            {% endif %}
            {% for num in paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ num }}">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

templates/partials/projects_list.html
<div class="row">
    <div class="col-9">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Create Date</th>
                <th scope="col">End Date</th>

                {% if perms.issue_tracker.change_project %}
                    <th scope="col">Edit</th>
                {% endif %}

                {% if perms.issue_tracker.delete_project %}
                    <th scope="col">Delete</th>
                {% endif %}

            </tr>
            </thead>
            <tbody>
            {% for project in projects %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'projects:project_detail' project.pk %}"
                       class="text-break">{{ project.title }}</a></td>
                <td class="text-break">{{ project.description }}</td>
                <td>{{ project.create_date }}</td>
                <td>
                    {% if project.end_date %}
                        {{ project.end_date }}
                    {% endif %}
                </td>

                {% if perms.issue_tracker.change_project %}
                    <td><a href="{% url 'projects:project_update' project.pk %}"
                           class="btn btn-primary">Edit</a></td>
                {% endif %}

                {% if perms.issue_tracker.delete_project %}
                    <td>
                        <form action="{% url 'projects:project_delete' project.pk %}" method="post">
                            {% csrf_token %}
                            {% include 'partials/delete_button.html' %}
                        </form>
                    </td>
                {% endif %}

            </tr>
            {% empty %}
            <tr>
                <td>
                    <h2>No projects yet</h2>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            {% include 'partials/pagination.html' %}
        {% endif %}
    </div>
    <div class="col-3">
        {% include 'partials/filtration.html' with btn_text='Filter' %}
    </div>
</div>

templates/partials/search.html
<form class="d-flex" action="{% url 'projects:search' %}" method="get">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="params">
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>

templates/partials/show_members.html
<li class="list-group-item d-none" id="showNewMember">
    <form action="{% url 'projects:project_add_member' project.pk %}" method="post">
        {% csrf_token %}
        <select name="user" id="" class="form-select">
            {% for obj in users_not_in_project %}
                <option value="{{ obj.pk }}">{{ obj.username }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-success mt-3 w-100">Add</button>
    </form>
</li>

templates/partials/submit_button.html
<button class="btn btn-success" type="submit">{{ btn_text | title | default:'Submit' }}</button>